#!/usr/bin/env python3
"""Generate TypeScript, Python, and Go contract types from JSON Schemas."""

from __future__ import annotations

import argparse
import json
import keyword
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from contract_schema import REPO_ROOT, SCHEMA_ROOT, SchemaStore, schema_paths


GENERATED_ROOT = REPO_ROOT / "contracts" / "generated"

HEADER = """// Code generated by tools/scripts/generate-contracts.py. DO NOT EDIT.
// Source of truth: contracts/schemas.
"""

PY_HEADER = '''"""Code generated by tools/scripts/generate-contracts.py. DO NOT EDIT.

Source of truth: contracts/schemas.
"""
'''

TOP_LEVEL_NAMES = {
    "repository.schema.json": "Repository",
    "change-request.schema.json": "ChangeRequest",
    "diff.schema.json": "Diff",
    "code-graph.schema.json": "CodeGraph",
    "review-standard.schema.json": "ReviewStandard",
    "context-bundle.schema.json": "ContextBundle",
    "finding.schema.json": "Finding",
    "review-run.schema.json": "ReviewRun",
    "provider.schema.json": "ProviderReferences",
    "publish.schema.json": "PublishableReview",
    "events/review-event.schema.json": "ReviewEvent",
    "llm/reviewer-output.schema.json": "ReviewerOutput",
}


@dataclass(frozen=True)
class NamedSchema:
    name: str
    schema_path: Path
    pointer: str
    schema: dict[str, Any]


class ContractGenerator:
    def __init__(self) -> None:
        self.store = SchemaStore()
        self.named: list[NamedSchema] = []
        self.name_by_ref: dict[tuple[Path, str], str] = {}
        self._collect_named_schemas()

    def outputs(self) -> dict[Path, str]:
        return {
            GENERATED_ROOT / "ts" / "package.json": self.ts_package_json(),
            GENERATED_ROOT / "ts" / "index.ts": self.typescript(),
            GENERATED_ROOT / "python" / "pyproject.toml": self.python_pyproject(),
            GENERATED_ROOT / "python" / "contract_types" / "__init__.py": self.python_init(),
            GENERATED_ROOT / "python" / "contract_types" / "types.py": self.python_types(),
            GENERATED_ROOT / "go" / "go.mod": self.go_mod(),
            GENERATED_ROOT / "go" / "contracts.go": format_go(self.go_types()),
        }

    def write(self, check: bool) -> list[str]:
        drift: list[str] = []
        for path, content in self.outputs().items():
            if check:
                if not path.exists() or path.read_text(encoding="utf-8") != content:
                    drift.append(str(path.relative_to(REPO_ROOT)))
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        return drift

    def _collect_named_schemas(self) -> None:
        used_names: set[str] = set()
        for path in schema_paths():
            relative = path.relative_to(SCHEMA_ROOT).as_posix()
            schema = self.store.schemas[path.resolve()]
            top_name = TOP_LEVEL_NAMES.get(relative)
            if top_name is not None:
                self._add_named(top_name, path, "", schema, used_names)

            defs = schema.get("$defs", {})
            if isinstance(defs, dict):
                for key, nested_schema in defs.items():
                    base = pascal_case(key)
                    name = base if base not in used_names else f"{top_name or pascal_case(path.stem.removesuffix('.schema'))}{base}"
                    self._add_named(name, path, f"/$defs/{escape_pointer(key)}", nested_schema, used_names)

    def _add_named(self, name: str, path: Path, pointer: str, schema: dict[str, Any], used_names: set[str]) -> None:
        used_names.add(name)
        resolved_path = path.resolve()
        self.name_by_ref[(resolved_path, pointer)] = name
        self.named.append(NamedSchema(name, resolved_path, pointer, schema))

    def ref_name(self, current_path: Path, ref: str) -> str | None:
        target_path, _ = self.store.resolve_ref(current_path, ref)
        _, fragment = split_ref(ref)
        return self.name_by_ref.get((target_path.resolve(), fragment))

    def ts_package_json(self) -> str:
        value = {
            "name": "@heimdall/contracts",
            "version": "0.0.0",
            "private": True,
            "type": "module",
            "exports": {"." : "./index.ts"},
            "types": "./index.ts",
        }
        return json.dumps(value, indent=2, sort_keys=True) + "\n"

    def python_pyproject(self) -> str:
        return """[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "heimdall-contracts"
version = "0.0.0"
requires-python = ">=3.12"

[tool.setuptools.packages.find]
where = ["."]
"""

    def python_init(self) -> str:
        names = [item.name for item in self.named]
        imports = ",\n    ".join(names)
        exported = ",\n    ".join(repr(name) for name in names)
        return f'''"""Generated Heimdall contract types."""

from .types import (
    {imports},
)

__all__ = [
    {exported},
]
'''

    def go_mod(self) -> str:
        return "module heimdall.dev/contracts/generated/go\n\ngo 1.22\n"

    def typescript(self) -> str:
        lines = [HEADER, ""]
        for item in self.named:
            lines.extend(self._ts_declaration(item))
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _ts_declaration(self, item: NamedSchema) -> list[str]:
        schema = item.schema
        description = schema.get("description")
        lines: list[str] = []
        if isinstance(description, str):
            lines.extend(ts_doc(description))

        if self._is_object_schema(schema):
            lines.append(f"export interface {item.name} {{")
            properties = schema.get("properties", {})
            required = set(schema.get("required", []))
            if isinstance(properties, dict):
                for key, nested_schema in properties.items():
                    optional = "" if key in required else "?"
                    lines.extend(indent(ts_doc(nested_schema.get("description")), "  "))
                    lines.append(f"  {quote_ts_key(key)}{optional}: {self.ts_type(nested_schema, item.schema_path)};")
            lines.append("}")
            return lines

        lines.append(f"export type {item.name} = {self.ts_type(schema, item.schema_path)};")
        return lines

    def ts_type(self, schema: dict[str, Any], current_path: Path) -> str:
        if "$ref" in schema:
            return self.ref_name(current_path, schema["$ref"]) or "unknown"
        if "oneOf" in schema:
            return " | ".join(self.ts_type(item, current_path) for item in schema["oneOf"])
        if "anyOf" in schema:
            return " | ".join(self.ts_type(item, current_path) for item in schema["anyOf"])
        if "enum" in schema and isinstance(schema["enum"], list):
            return " | ".join(json.dumps(value) for value in schema["enum"])

        schema_type = schema.get("type")
        if schema_type == "string":
            return "string"
        if schema_type in ("integer", "number"):
            return "number"
        if schema_type == "boolean":
            return "boolean"
        if schema_type == "array":
            item_type = self.ts_type(schema.get("items", {}), current_path)
            return f"Array<{item_type}>"
        if schema_type == "object":
            return self.ts_object_type(schema, current_path)
        return "unknown"

    def ts_object_type(self, schema: dict[str, Any], current_path: Path) -> str:
        properties = schema.get("properties")
        additional = schema.get("additionalProperties")
        if isinstance(properties, dict) and properties:
            required = set(schema.get("required", []))
            fields = []
            for key, nested_schema in properties.items():
                optional = "" if key in required else "?"
                fields.append(f"{quote_ts_key(key)}{optional}: {self.ts_type(nested_schema, current_path)}")
            return "{ " + "; ".join(fields) + " }"
        if isinstance(additional, dict):
            property_names = schema.get("propertyNames")
            if isinstance(property_names, dict) and isinstance(property_names.get("enum"), list):
                key_type = " | ".join(json.dumps(value) for value in property_names["enum"])
                return f"Partial<Record<{key_type}, {self.ts_type(additional, current_path)}>>"
            return f"Record<string, {self.ts_type(additional, current_path)}>"
        return "Record<string, unknown>"

    def python_types(self) -> str:
        lines = [
            PY_HEADER,
            "from __future__ import annotations",
            "",
            "from dataclasses import dataclass, field",
            "from typing import Any, Literal",
            "",
        ]
        for item in self.named:
            lines.extend(self._python_declaration(item))
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _python_declaration(self, item: NamedSchema) -> list[str]:
        schema = item.schema
        if self._is_object_schema(schema):
            lines = [f"@dataclass(slots=True)", f"class {item.name}:"]
            properties = schema.get("properties", {})
            required = set(schema.get("required", []))
            ordered_keys = [key for key in properties if key in required] + [key for key in properties if key not in required]
            if not ordered_keys:
                lines.append("    pass")
                return lines
            for key in ordered_keys:
                nested_schema = properties[key]
                field_type = self.python_type(nested_schema, item.schema_path)
                field_name = python_field_name(key)
                if key in required:
                    suffix = "" if field_name == key else f" = field(metadata={{\"json_name\": {key!r}}})"
                    lines.append(f"    {field_name}: {field_type}{suffix}")
                elif field_name == key:
                    lines.append(f"    {field_name}: {field_type} | None = None")
                else:
                    lines.append(f"    {field_name}: {field_type} | None = field(default=None, metadata={{\"json_name\": {key!r}}})")
            return lines
        return [f"{item.name} = {self.python_type(schema, item.schema_path)}"]

    def python_type(self, schema: dict[str, Any], current_path: Path) -> str:
        if "$ref" in schema:
            return self.ref_name(current_path, schema["$ref"]) or "Any"
        if "oneOf" in schema:
            return " | ".join(self.python_type(item, current_path) for item in schema["oneOf"])
        if "anyOf" in schema:
            return " | ".join(self.python_type(item, current_path) for item in schema["anyOf"])
        if "enum" in schema and isinstance(schema["enum"], list):
            return "Literal[" + ", ".join(repr(value) for value in schema["enum"]) + "]"

        schema_type = schema.get("type")
        if schema_type == "string":
            return "str"
        if schema_type == "integer":
            return "int"
        if schema_type == "number":
            return "float"
        if schema_type == "boolean":
            return "bool"
        if schema_type == "array":
            return f"list[{self.python_type(schema.get('items', {}), current_path)}]"
        if schema_type == "object":
            additional = schema.get("additionalProperties")
            if isinstance(additional, dict):
                return f"dict[str, {self.python_type(additional, current_path)}]"
            return "dict[str, Any]"
        return "Any"

    def go_types(self) -> str:
        lines = [
            HEADER.replace("//", "//"),
            "",
            "package contracts",
            "",
        ]
        for item in self.named:
            lines.extend(self._go_declaration(item))
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _go_declaration(self, item: NamedSchema) -> list[str]:
        schema = item.schema
        if self._is_object_schema(schema):
            lines = [f"type {item.name} struct {{"]
            properties = schema.get("properties", {})
            required = set(schema.get("required", []))
            for key, nested_schema in properties.items():
                field_name = pascal_case(key)
                field_type = self.go_type(nested_schema, item.schema_path, key in required)
                tag = key if key in required else f"{key},omitempty"
                lines.append(f"\t{field_name} {field_type} `json:\"{tag}\"`")
            lines.append("}")
            return lines
        return [f"type {item.name} {self.go_type(schema, item.schema_path, True)}"]

    def go_type(self, schema: dict[str, Any], current_path: Path, required: bool) -> str:
        raw_type = self._go_raw_type(schema, current_path)
        if required or raw_type.startswith(("[]", "map[")) or raw_type == "any":
            return raw_type
        return f"*{raw_type}"

    def _go_raw_type(self, schema: dict[str, Any], current_path: Path) -> str:
        if "$ref" in schema:
            return self.ref_name(current_path, schema["$ref"]) or "any"
        if "oneOf" in schema or "anyOf" in schema:
            return "any"
        schema_type = schema.get("type")
        if schema_type == "string" or "enum" in schema:
            return "string"
        if schema_type == "integer":
            return "int"
        if schema_type == "number":
            return "float64"
        if schema_type == "boolean":
            return "bool"
        if schema_type == "array":
            return f"[]{self.go_type(schema.get('items', {}), current_path, True)}"
        if schema_type == "object":
            additional = schema.get("additionalProperties")
            if isinstance(additional, dict):
                return f"map[string]{self.go_type(additional, current_path, True)}"
            return "map[string]any"
        return "any"

    def _is_object_schema(self, schema: dict[str, Any]) -> bool:
        return schema.get("type") == "object" and isinstance(schema.get("properties"), dict)


def split_ref(ref: str) -> tuple[str, str]:
    if "#" not in ref:
        return ref, ""
    path, fragment = ref.split("#", 1)
    return path, fragment


def pascal_case(value: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", value)
    return "".join(word[:1].upper() + word[1:] for word in words) or "Value"


def escape_pointer(value: str) -> str:
    return value.replace("~", "~0").replace("/", "~1")


def quote_ts_key(key: str) -> str:
    return key if re.match(r"^[A-Za-z_$][A-Za-z0-9_$]*$", key) else json.dumps(key)


def python_field_name(key: str) -> str:
    if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", key) and not keyword.iskeyword(key):
        return key
    return f"{key}_"


def ts_doc(value: Any) -> list[str]:
    if not isinstance(value, str) or not value.strip():
        return []
    cleaned = " ".join(value.split())
    return ["/** " + cleaned.replace("*/", "* /") + " */"]


def indent(lines: list[str], prefix: str) -> list[str]:
    return [prefix + line for line in lines]


def format_go(content: str) -> str:
    try:
        result = subprocess.run(["gofmt"], input=content, text=True, capture_output=True, check=False)
    except FileNotFoundError:
        return content
    if result.returncode != 0:
        return content
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check generated files for drift without writing")
    args = parser.parse_args()

    try:
        generator = ContractGenerator()
        drift = generator.write(check=args.check)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1

    if drift:
        print("Generated contract files are out of date:", file=sys.stderr)
        for path in drift:
            print(f"  {path}", file=sys.stderr)
        print("Run `pnpm contracts:generate` from the repository root.", file=sys.stderr)
        return 1

    action = "Checked" if args.check else "Generated"
    print(f"{action} {len(generator.outputs())} contract artifact files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
