export {
  type ChunkKind,
  ChunkKindSchema,
  type ChunkRecord,
  ChunkRecordSchema,
  type DependencyRecord,
  DependencyRecordSchema,
  type DependencyType,
  DependencyTypeSchema,
  type DiagnosticRecord,
  DiagnosticRecordSchema,
  type DiagnosticSeverity,
  DiagnosticSeveritySchema,
  type EdgeRecord,
  EdgeRecordSchema,
  type FileRecord,
  FileRecordSchema,
  INDEX_RECORD_SCHEMA_VERSION,
  type IndexNodeKind,
  IndexNodeKindSchema,
  type IndexRecord,
  IndexRecordSchema,
  isSupportedIndexRecordVersion,
  type RouteRecord,
  RouteRecordSchema,
  type SymbolRecord,
  SymbolRecordSchema,
  type SymbolVisibility,
  SymbolVisibilitySchema,
  type TestMappingRecord,
  TestMappingRecordSchema,
} from "@repo/index-schema";
