import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { validateIndexArtifact } from "@repo/indexer-driver";
import { describe, expect, it } from "vitest";
import { indexTypeScriptRepository } from "../src/index";

describe("indexTypeScriptRepository", () => {
  it("emits files, symbols, chunks, and edges for TypeScript sources", async () => {
    const workspacePath = await mkdtemp(join(tmpdir(), "heimdall-indexer-ts-"));
    await writeFile(
      join(workspacePath, "service.ts"),
      [
        'import { readFile } from "node:fs/promises";',
        "",
        "export class Service {",
        "  async load(path: string) {",
        "    return parse(await readFile(path, 'utf8'));",
        "  }",
        "}",
        "",
        "function parse(input: string) {",
        "  return input.trim();",
        "}",
      ].join("\n"),
    );

    const artifact = await indexTypeScriptRepository({
      repoId: "repo_123",
      commitSha: "1234567890abcdef",
      workspacePath,
    });

    expect(artifact.manifest.fileCount).toBe(1);
    expect(
      artifact.records.some((record) => record.type === "symbol" && record.name === "Service"),
    ).toBe(true);
    expect(artifact.records.some((record) => record.type === "chunk")).toBe(true);
    expect(
      artifact.records.some((record) => record.type === "edge" && record.kind === "imports"),
    ).toBe(true);
    expect(
      artifact.records.some((record) => record.type === "edge" && record.kind === "calls"),
    ).toBe(true);
    expect(validateIndexArtifact(artifact)).toEqual([]);
  });

  it("skips generated and vendored sources before emitting records", async () => {
    const workspacePath = await mkdtemp(join(tmpdir(), "heimdall-indexer-ts-"));
    await Promise.all([
      mkdir(join(workspacePath, "src", "generated"), { recursive: true }),
      mkdir(join(workspacePath, "src", "__generated__"), { recursive: true }),
      mkdir(join(workspacePath, "vendor"), { recursive: true }),
      mkdir(join(workspacePath, "node_modules", "pkg"), { recursive: true }),
      mkdir(join(workspacePath, "dist"), { recursive: true }),
    ]);
    await Promise.all([
      writeFile(join(workspacePath, "src", "app.ts"), "export const app = true;\n"),
      writeFile(
        join(workspacePath, "src", "generated", "client.ts"),
        "export const generatedClient = true;\n",
      ),
      writeFile(
        join(workspacePath, "src", "__generated__", "types.ts"),
        "export type GeneratedType = string;\n",
      ),
      writeFile(join(workspacePath, "src", "api.generated.ts"), "export const api = true;\n"),
      writeFile(
        join(workspacePath, "src", "content-marker.ts"),
        ["// Code generated by a test fixture. DO NOT EDIT.", "export const marker = true;"].join(
          "\n",
        ),
      ),
      writeFile(join(workspacePath, "vendor", "jquery.js"), "export const vendored = true;\n"),
      writeFile(
        join(workspacePath, "node_modules", "pkg", "index.js"),
        "export const dependency = true;\n",
      ),
      writeFile(join(workspacePath, "dist", "bundle.js"), "export const bundle = true;\n"),
    ]);

    const artifact = await indexTypeScriptRepository({
      repoId: "repo_123",
      commitSha: "1234567890abcdef",
      workspacePath,
    });

    const filePaths = artifact.records.flatMap((record) =>
      record.type === "file" ? [record.path] : [],
    );
    expect(filePaths).toEqual(["src/app.ts"]);
    expect(artifact.manifest.fileCount).toBe(1);
    expect(validateIndexArtifact(artifact)).toEqual([]);
  });
});
