import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { inspect } from "node:util";
import type { ChangedFile, PullRequestSnapshot } from "@repo/contracts";
import {
  runStaticAnalysis,
  type StaticAnalysisReport,
  type StaticAnalysisRequest,
  type StaticToolName,
} from "@repo/static-analysis";
import { createLocalToolRunner } from "@repo/tool-runner";

/** Product-safe proof emitted by the local static-analysis smoke. */
type LocalStaticAnalysisSmokeProof = {
  /** Go static-analysis proof summary. */
  readonly go: LanguageSmokeProof;
  /** Rust static-analysis proof summary. */
  readonly rust: LanguageSmokeProof;
  /** Status of the smoke run. */
  readonly status: "passed";
  /** Toolchain versions observed by the smoke when available. */
  readonly toolchain: {
    /** Go version string from the report environment. */
    readonly go: "available";
    /** Cargo version string from the report environment. */
    readonly cargo: "available";
  };
};

/** Product-safe proof for one language smoke report. */
type LanguageSmokeProof = {
  /** Static-analysis report status. */
  readonly reportStatus: StaticAnalysisReport["status"];
  /** Number of normalized diagnostics parsed from live tool output. */
  readonly diagnosticCount: number;
  /** New diagnostic count after report construction. */
  readonly newDiagnosticCount: number;
  /** Tool summaries emitted by the report. */
  readonly tools: readonly ToolSmokeProof[];
};

/** Product-safe proof for one static-analysis tool run. */
type ToolSmokeProof = {
  /** Number of normalized diagnostics attributed to the tool. */
  readonly diagnosticCount: number;
  /** Process exit code, when available. */
  readonly exitCode: number | null;
  /** Tool run status. */
  readonly status: StaticAnalysisReport["toolRuns"][number]["status"];
  /** Static-analysis tool name. */
  readonly tool: StaticToolName;
};

/** Runs local Go and Rust static-analysis tools against generated throwaway projects. */
async function main(): Promise<void> {
  const root = await mkdtemp(join(tmpdir(), "heimdall-static-analysis-smoke-"));

  try {
    const goWorkspace = join(root, "go");
    const rustWorkspace = join(root, "rust");
    await Promise.all([writeGoFixture(goWorkspace), writeRustFixture(rustWorkspace)]);

    const runner = createLocalToolRunner();
    const [goReport, rustReport] = await Promise.all([
      runStaticAnalysis({
        request: smokeRequest({
          changedFile: changedFile("pkg/foo.go", "go", 6),
          repoId: "repo_static_smoke_go",
          requestedTools: ["go_vet"],
          reviewRunId: "rrn_static_smoke_go",
          workspacePath: goWorkspace,
        }),
        runner,
      }),
      runStaticAnalysis({
        request: smokeRequest({
          changedFile: changedFile("src/lib.rs", "rust", 2),
          repoId: "repo_static_smoke_rust",
          requestedTools: ["cargo_check", "cargo_clippy"],
          reviewRunId: "rrn_static_smoke_rust",
          workspacePath: rustWorkspace,
        }),
        runner,
      }),
    ]);

    assertSmokeReport("go", goReport, ["go_vet"]);
    assertSmokeReport("rust", rustReport, ["cargo_check", "cargo_clippy"]);

    const proof: LocalStaticAnalysisSmokeProof = {
      go: languageProof(goReport),
      rust: languageProof(rustReport),
      status: "passed",
      toolchain: {
        cargo: "available",
        go: "available",
      },
    };
    console.log(JSON.stringify(proof, null, 2));
  } finally {
    await rm(root, { force: true, recursive: true });
  }
}

/** Writes a minimal Go module with one vet-detectable issue. */
async function writeGoFixture(workspacePath: string): Promise<void> {
  await mkdir(join(workspacePath, "pkg"), { recursive: true });
  await Promise.all([
    writeFile(
      join(workspacePath, "go.mod"),
      ["module example.com/heimdall-static-smoke", "", "go 1.22", ""].join("\n"),
      "utf8",
    ),
    writeFile(
      join(workspacePath, "pkg/foo.go"),
      [
        "package pkg",
        "",
        'import "fmt"',
        "",
        "func Smoke() {",
        '  fmt.Printf("%d", "text")',
        "}",
        "",
      ].join("\n"),
      "utf8",
    ),
  ]);
}

/** Writes a minimal Rust crate with one compiler warning. */
async function writeRustFixture(workspacePath: string): Promise<void> {
  await mkdir(join(workspacePath, "src"), { recursive: true });
  await Promise.all([
    writeFile(
      join(workspacePath, "Cargo.toml"),
      [
        "[package]",
        'name = "heimdall_static_smoke"',
        'version = "0.1.0"',
        'edition = "2021"',
        "",
        "[lib]",
        'path = "src/lib.rs"',
        "",
      ].join("\n"),
      "utf8",
    ),
    writeFile(
      join(workspacePath, "Cargo.lock"),
      [
        "# This file is automatically @generated by Cargo.",
        "# It is not intended for manual editing.",
        "version = 4",
        "",
        "[[package]]",
        'name = "heimdall_static_smoke"',
        'version = "0.1.0"',
        "",
      ].join("\n"),
      "utf8",
    ),
    writeFile(
      join(workspacePath, "src/lib.rs"),
      ["pub fn smoke() -> i32 {", "    let value = 1;", "    2", "}", ""].join("\n"),
      "utf8",
    ),
  ]);
}

/** Builds a static-analysis request for one local smoke fixture. */
function smokeRequest(input: {
  /** Changed file used to select static-analysis tools. */
  readonly changedFile: ChangedFile;
  /** Repository ID used for product-safe report IDs. */
  readonly repoId: string;
  /** Tool allowlist for this smoke request. */
  readonly requestedTools: readonly StaticToolName[];
  /** Review run ID used for product-safe report IDs. */
  readonly reviewRunId: string;
  /** Local throwaway workspace path. */
  readonly workspacePath: string;
}): StaticAnalysisRequest {
  return {
    createdAt: "2026-05-08T00:00:00.000Z",
    mode: "changed_files_fast",
    orgId: "org_static_smoke",
    reason: "manual",
    repoId: input.repoId,
    requestedTools: input.requestedTools,
    reviewRunId: input.reviewRunId,
    schemaVersion: "static_analysis_request.v1",
    snapshot: smokeSnapshot(input.repoId, input.changedFile),
    workspace: {
      commitSha: "smoke_head",
      isTrusted: true,
      path: input.workspacePath,
      workspaceId: `ws_${input.repoId}`,
    },
  };
}

/** Builds a minimal pull request snapshot for local static-analysis smoke planning. */
function smokeSnapshot(repoId: string, changedFile: ChangedFile): PullRequestSnapshot {
  return {
    additions: 1,
    authorLogin: "heimdall-smoke",
    baseRef: "main",
    baseSha: "smoke_base",
    changedFileCount: 1,
    changedFiles: [changedFile],
    deletions: 0,
    diffHash: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    fetchedAt: "2026-05-08T00:00:00.000Z",
    headRef: "heimdall-static-smoke",
    headSha: "smoke_head",
    installationId: "inst_static_smoke",
    isDraft: false,
    labels: [],
    provider: "github",
    providerPullRequestId: "1",
    providerRepoId: "1",
    pullRequestNumber: 1,
    repoId,
    schemaVersion: "pull_request_snapshot.v1",
    snapshotId: `prs_${repoId}`,
    state: "open",
    title: "Static analysis smoke",
  };
}

/** Builds a minimal changed-file record with one added line. */
function changedFile(
  path: string,
  language: ChangedFile["language"],
  changedLine: number,
): ChangedFile {
  return {
    additions: 1,
    changes: 1,
    deletions: 0,
    hunks: [
      {
        header: `@@ -${changedLine},0 +${changedLine},1 @@`,
        hunkId: `hunk_${path.replaceAll(/[^A-Za-z0-9]/gu, "_")}`,
        lines: [{ content: "static analysis smoke", kind: "addition", newLine: changedLine }],
        newLines: 1,
        newStart: changedLine,
        oldLines: 0,
        oldStart: changedLine,
      },
    ],
    isBinary: false,
    isGenerated: false,
    isTest: false,
    language,
    path,
    status: "modified",
  };
}

/** Verifies that the smoke report exercised expected tools and parsed diagnostics. */
function assertSmokeReport(
  language: "go" | "rust",
  report: StaticAnalysisReport,
  expectedTools: readonly StaticToolName[],
): void {
  const observedTools = new Set(report.toolRuns.map((toolRun) => toolRun.tool));
  const missingTools = expectedTools.filter((tool) => !observedTools.has(tool));
  if (missingTools.length > 0) {
    throw new Error(`${language} static-analysis smoke did not run: ${missingTools.join(", ")}`);
  }
  if (report.summary.diagnosticCount < 1) {
    throw new Error(`${language} static-analysis smoke parsed no diagnostics.`);
  }
}

/** Converts a static-analysis report into product-safe smoke proof. */
function languageProof(report: StaticAnalysisReport): LanguageSmokeProof {
  return {
    diagnosticCount: report.summary.diagnosticCount,
    newDiagnosticCount: report.summary.newDiagnosticCount,
    reportStatus: report.status,
    tools: report.toolRuns.map((toolRun) => ({
      diagnosticCount: toolRun.diagnosticCount,
      exitCode: toolRun.exitCode,
      status: toolRun.status,
      tool: toolRun.tool,
    })),
  };
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? (error.stack ?? error.message) : inspect(error));
  process.exitCode = 1;
});
