FROM oven/bun:1.3.9

WORKDIR /workspace

RUN bun install --global pnpm@10.33.3 && pnpm --version

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc turbo.json tsconfig.json tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @app/worker... build

ENV NODE_ENV=production

CMD ["pnpm", "--filter", "@app/worker", "start"]
